name: local-mds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - pandas
      - mimesis
      - duckdb
      - dbt-duckdb
      - streamlit
      - metricflow==0.140.0
